repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.4.1
      hooks:
          # Run the linter.
          - id: ruff
            args:
                [--fix]
                # Run the formatter.
          - id: ruff-format
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: check-json
          - id: check-yaml
          - id: end-of-file-fixer
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.15.2
      hooks:
          - id: pyupgrade
            args: [--py3-plus, --py38-plus]
#   - repo: https://github.com/pycqa/pydocstyle
#     rev: 5.1.1  # pick a git hash / tag to point to
#     hooks:
#       - id: pydocstyle
#         exclude: test_*
